stages:
  - build
  - build2
  - publish

default:
  before_script:
    # Our build agent are supposed to define these variables to enable
    # build parallelization using a number of cores appropriate for
    # the agent.  However we have had cases where they were not
    # defined, slowing down the builds.  This should help us debug
    # these situations.
    - echo "MAKEFLAGS='$MAKEFLAGS' NBPROC='$NBPROC'"
    - cat /sys/fs/cgroup/cpuset.cpus || cat /sys/fs/cgroup/cpuset/cpuset.cpus || true

alpine-gcc:
  stage: build
  only:
    - branches
  except:
    - /wip/
  image: gitlab-registry.lrde.epita.fr/spot/buildenv/alpine
  script:
    - autoreconf -vfi
    - ./configure
    - make
    - make check LOG_DRIVER=$PWD/tools/test-driver.stat
  after_script:
    - cd tests && ../tools/tests2junit > junit.xml
  artifacts:
    when: always
    paths:
      - tests/*/*.log
      - ./*.log
    reports:
      junit: tests/junit.xml
